version: '3'
services:
  app:
    container_name: full_app
    build: ./backend
    ports: 
      - 8080:3000 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres       

    networks:
      - fullstack


  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    depends_on:
      - fullstack-postgres
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped

  reactapp:
    container_name: react-app
    build: ./frontend
    command: yarn run start
    ports: 
    - "3000:8080"
    volumes:
      - .:/user/app/vue


volumes:
  api:
  database_postgres:   
  reactapp:

networks:
  fullstack:
    driver: bridge